# Weakly monotonic combinations

Given an alphabet of size n, how many string of length k can we form such that each subsequent character is either identical to or occurs later in the alphabet than the previous character? For example, given an alphabet {A, B, C, D} and string of length 4, the following 20 strings satisfy this condition. 

DDD, CDD, CCD, CCC, BDD, BCD, BCC, BBC, BBC, BBB, ADD, ACD, ACC, ABD, ABC, ABB, AAD, AAC, AAB, AAA

These can be found by starting with the allowed strings of length one

D, C, B, A

and then noting that strings of length two could be obtained by prepending D to the first string of length one, C to the first two strings of length one and so on.

DD, CD, CC, BD, BC, BB, AD, AC, AB, AA

Strings of length three are then obtained by prepending D to the first string of length two, C to the first three strings of length two etc.

To get the number of strings satisfying the conditions, we start with the array \[1, 1, 1, 1\], which represents the number of string of length one starting with D, C, B and A, respectively. We then apply the cummulative sum operation to get a new array representing the number of strings of length two starting with D, C, B and A. Applying recursively, we can find the numbers of strings of length k starting with each character. The total number of allowed strings of length k is then simply the sum over this array.

```
k  array         # allowed strings
1  [1 1 1 1]       4
2  [1 2 3 4]      10
3  [1 3 6 10]     20
4  [1 4 10 20]    35
5  [1 5 15 35]    56
```


In [1]:
import numpy as np

In [28]:
n = 4 # size of alphabet
k = 5 # string length

b = np.ones(n, dtype=np.uint)
print(b, np.sum(b))

for j in range(2, k+1):
    b = np.cumsum(b)
    print(b, np.sum(b))

[1 1 1 1] 4
[1 2 3 4] 10
[ 1  3  6 10] 20
[ 1  4 10 20] 35
[ 1  5 15 35] 56


In [25]:
b[0]

1